[virtual_force_publisher] Calcualte sr-inverse
jsk-ros-pkg/jsk_common pull request #1731
Opened 2022-05-19 11:57 UTC by iory

# What is this?

Use SR-inverse for calculating Jacobian.
Without this PR, he virtual force around the singularity becomes strange as follows.

2022-05-19 11:58 UTC, iory commented
@Naoki-Hiraoka Could you review this PR?

2022-05-23 07:45 UTC, Naoki-Hiraoka requested changes
計算内容自体は変わらないのですが、`calculateSRInverse`の引数に`jacobian_`を入れるのではなく、`jac_t`を入れる形にした方が分かりやすいのではないかと思いました。

(メモ)
逆運動学のときは`p = J q`を解くが、接触力推定のときは`f = -J^t /tau`を解くため、`J`ではなく`J^t`の疑似逆行列を計算することになる. また、逆運動学のときはSR-inverseとして `J^t (J J^t + k)^-1` と `(J^t J + k)^-1 J^t`の2種類の計算法がある中で、 J の行数が列数よりも小さいことが多いので前者を使うことが多いが、接触力推定のときはJ^t の列数が行数よりも小さいことが多いので後者を使う.

2022-05-23 09:22 UTC, iory commented on virtual_force_publisher/src/virtual_force_publisher.cpp
> +		jac_t_pseudo_inv = calculateSRInverse(jacobian_.data);
ありがとうございます！変更しました。
https://github.com/jsk-ros-pkg/jsk_common/pull/1731/commits/60e7b004340c0079adf24db730a04dd6dfb0e768

> 逆運動学のときはSR-inverseとして J^t (J J^t + k)^-1 と (J^t J + k)^-1 J^tの2種類の計算法がある中で、 J の行数が列数よりも小さいことが多いので前者を使うことが多いが、接触力推定のときはJ^t の列数が行数よりも小さいことが多いので後者を使う.

この変更も加えてほうが良さそうでしょうか？

2022-05-23 09:25 UTC, Naoki-Hiraoka commented on virtual_force_publisher/src/virtual_force_publisher.cpp
> +		jac_t_pseudo_inv = calculateSRInverse(jacobian_.data);
実はもとの @iory さんの実装がそうなっていたので、大丈夫です。

2022-05-23 10:11 UTC, Naoki-Hiraoka commented on virtual_force_publisher/src/virtual_force_publisher.cpp
> +		jac_t_pseudo_inv = calculateSRInverse(jacobian_.data);
ベターだと思います。

このような条件分岐をやっていないライブラリが多いので必須ではないと思いますが、多少高速化の効果があると思います。
https://github.com/euslisp/jskeus/blob/c4b9a113b0dcb15a41dd96a3767df6f1905386af/irteus/irtmath.l#L330
https://github.com/fkanehiro/hrpsys-base/blob/798b4c9904c273d0217a434bec35c92207b1274d/rtc/ImpedanceController/JointPathEx.cpp#L42

2022-05-23 11:27 UTC, iory commented on virtual_force_publisher/src/virtual_force_publisher.cpp
> +		jac_t_pseudo_inv = calculateSRInverse(jacobian_.data);
ありがとうございます！
https://github.com/jsk-ros-pkg/jsk_common/pull/1731/commits/2ea61b2c021dca23d72b72fc7519c0063c8b68bb
変更を加えました。

2022-06-03 05:23 UTC, merged