[jsk_topic_tools] Fix filename in doc: static_transform_republisher->static_tf_republisher
jsk-ros-pkg/jsk_common pull request #1741
Opened 2022-06-03 07:53 UTC by nakane11

File name static_transform_republisher.py in documentation is wrong, so usage written here does not work.

2022-06-03 07:54 UTC, iory requested changes

2022-06-03 07:54 UTC, iory commented on doc/jsk_topic_tools/scripts/static_tf_republisher.rst
>  ===============================
Could you also change the `=` to ```==================```

2022-06-03 12:45 UTC, knorth55 approved these changes

2022-06-03 12:52 UTC, k-okada commented
@knorth55 thank you for review and approve. When you approve, I got notification email, that is good chance to merge the PR, but if the CI not finished, I have to wait CI, but usually I forget about this PR. So if you approve AFTER CI passed, I can push merge button immediately.

2022-06-03 13:23 UTC, nakane11 commented
I found the same commit in #1709 eea60a5

2022-06-04 09:20 UTC, iory approved these changes

2022-06-04 09:22 UTC, iory commented
> I found the same commit in #1709 eea60a5

This PR is good because the commit granularity focuses on modifying the document.

2022-06-05 08:30 UTC, merged